spring:
  application:
    name: pancakes_unlimited
  datasource:
    url: jdbc:postgresql://localhost:5432/pancakes_unlimited_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: false